"""m2 mock tables: empty_rooms + library_seats (tool_query deterministic tools)

Revision ID: 252f1aa7a5c3
Revises: 9ef538c8bad3
Create Date: 2026-08-16 18:16:05.520602

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '252f1aa7a5c3'
down_revision: str | Sequence[str] | None = '9ef538c8bad3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empty_rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('building', sa.String(length=16), nullable=False),
    sa.Column('room', sa.String(length=16), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empty_rooms'))
    )
    op.create_index(op.f('ix_empty_rooms_building'), 'empty_rooms', ['building'], unique=False)
    op.create_table('library_seats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('floor', sa.String(length=8), nullable=False),
    sa.Column('free_seats', sa.Integer(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_library_seats'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('library_seats')
    op.drop_index(op.f('ix_empty_rooms_building'), table_name='empty_rooms')
    op.drop_table('empty_rooms')
    # ### end Alembic commands ###
