"""fc tools expansion

Revision ID: 42845db34626
Revises: 8d4f2a6c9e01
Create Date: 2026-08-19 13:14:18.348591

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '42845db34626'
down_revision: str | Sequence[str] | None = '8d4f2a6c9e01'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_calendar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term', sa.String(length=16), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('label', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_calendar'))
    )
    op.create_index(op.f('ix_academic_calendar_term'), 'academic_calendar', ['term'], unique=False)
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcements'))
    )
    op.create_index(op.f('ix_announcements_publish_date'), 'announcements', ['publish_date'], unique=False)
    op.create_table('card_balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_no', sa.String(length=32), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_balances'))
    )
    op.create_index(op.f('ix_card_balances_student_no'), 'card_balances', ['student_no'], unique=False)
    op.create_table('dorm_power',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('building', sa.String(length=16), nullable=False),
    sa.Column('room', sa.String(length=16), nullable=False),
    sa.Column('power_left', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dorm_power'))
    )
    op.create_index(op.f('ix_dorm_power_building'), 'dorm_power', ['building'], unique=False)
    op.create_table('exam_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_no', sa.String(length=32), nullable=False),
    sa.Column('term', sa.String(length=16), nullable=False),
    sa.Column('course', sa.String(length=64), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('exam_time', sa.String(length=16), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_schedules'))
    )
    op.create_index(op.f('ix_exam_schedules_student_no'), 'exam_schedules', ['student_no'], unique=False)
    op.create_index(op.f('ix_exam_schedules_term'), 'exam_schedules', ['term'], unique=False)
    op.create_table('exam_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_no', sa.String(length=32), nullable=False),
    sa.Column('term', sa.String(length=16), nullable=False),
    sa.Column('course', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_scores'))
    )
    op.create_index(op.f('ix_exam_scores_student_no'), 'exam_scores', ['student_no'], unique=False)
    op.create_index(op.f('ix_exam_scores_term'), 'exam_scores', ['term'], unique=False)
    op.create_table('library_borrows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_no', sa.String(length=32), nullable=False),
    sa.Column('book_title', sa.String(length=64), nullable=False),
    sa.Column('borrow_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_library_borrows'))
    )
    op.create_index(op.f('ix_library_borrows_student_no'), 'library_borrows', ['student_no'], unique=False)
    op.create_table('lost_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.Column('lost_date', sa.Date(), nullable=False),
    sa.Column('reporter', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lost_items'))
    )
    op.create_index(op.f('ix_lost_items_item_name'), 'lost_items', ['item_name'], unique=False)
    op.create_index(op.f('ix_lost_items_location'), 'lost_items', ['location'], unique=False)
    op.create_table('shuttle_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('line', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('depart_time', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shuttle_schedules'))
    )
    op.create_index(op.f('ix_shuttle_schedules_line'), 'shuttle_schedules', ['line'], unique=False)
    op.create_table('timetables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_no', sa.String(length=32), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('course', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.Column('teacher', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timetables'))
    )
    op.create_index(op.f('ix_timetables_student_no'), 'timetables', ['student_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetables_student_no'), table_name='timetables')
    op.drop_table('timetables')
    op.drop_index(op.f('ix_shuttle_schedules_line'), table_name='shuttle_schedules')
    op.drop_table('shuttle_schedules')
    op.drop_index(op.f('ix_lost_items_location'), table_name='lost_items')
    op.drop_index(op.f('ix_lost_items_item_name'), table_name='lost_items')
    op.drop_table('lost_items')
    op.drop_index(op.f('ix_library_borrows_student_no'), table_name='library_borrows')
    op.drop_table('library_borrows')
    op.drop_index(op.f('ix_exam_scores_term'), table_name='exam_scores')
    op.drop_index(op.f('ix_exam_scores_student_no'), table_name='exam_scores')
    op.drop_table('exam_scores')
    op.drop_index(op.f('ix_exam_schedules_term'), table_name='exam_schedules')
    op.drop_index(op.f('ix_exam_schedules_student_no'), table_name='exam_schedules')
    op.drop_table('exam_schedules')
    op.drop_index(op.f('ix_dorm_power_building'), table_name='dorm_power')
    op.drop_table('dorm_power')
    op.drop_index(op.f('ix_card_balances_student_no'), table_name='card_balances')
    op.drop_table('card_balances')
    op.drop_index(op.f('ix_announcements_publish_date'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_academic_calendar_term'), table_name='academic_calendar')
    op.drop_table('academic_calendar')
    # ### end Alembic commands ###
