"""m5 conversations messages

Revision ID: 4ef6ca43cc7d
Revises: 42845db34626
Create Date: 2026-08-20 00:09:41.045987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef6ca43cc7d'
down_revision: Union[str, Sequence[str], None] = '42845db34626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('title_source', sa.String(length=8), nullable=False),
    sa.Column('handoff', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('thread_id', name=op.f('uq_conversations_thread_id'))
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('route', sa.String(length=16), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.Column('pending_question', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.Text(), nullable=False),
    sa.Column('status_events', sa.Text(), nullable=False),
    sa.Column('sources', sa.Text(), nullable=False),
    sa.Column('error', sa.Boolean(), nullable=False),
    sa.Column('feedback_submitted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    ⚠️ 顺序修正（真实环境冒烟踩坑）：MySQL 必须先删外键约束再删索引，
    否则报 1553 "Cannot drop index: needed in a foreign key constraint"。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('fk_messages_conversation_id_conversations'), 'messages', type_='foreignkey'
    )
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
