"""zjut m1: drop ticket tables, add knowledge_entries/bad_cases

Revision ID: 9ef538c8bad3
Revises: d6e41f2a9b80
Create Date: 2026-08-15 22:47:00.853389

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9ef538c8bad3'
down_revision: str | Sequence[str] | None = 'd6e41f2a9b80'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bad_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('reply', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bad_cases'))
    )
    op.create_index(op.f('ix_bad_cases_status'), 'bad_cases', ['status'], unique=False)
    op.create_index(op.f('ix_bad_cases_user_id'), 'bad_cases', ['user_id'], unique=False)
    op.create_table('knowledge_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=16), nullable=False),
    sa.Column('keywords', sa.String(length=128), nullable=False),
    sa.Column('question', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_entries'))
    )
    op.create_index(op.f('ix_knowledge_entries_domain'), 'knowledge_entries', ['domain'], unique=False)
    # Drop order matters (MySQL FK): child tables before parents.
    # ticket_logs FK->tickets; tickets FK->users/repairmen.
    # drop_table 连带删除表内索引与 FK（FK 依赖索引不能单独 drop，见 1553）。
    op.drop_table('ticket_logs')
    op.drop_table('tickets')
    op.drop_table('repairmen')
    op.drop_table('dorms')
    op.drop_table('accounts')
    op.drop_table('announcements')
    op.drop_table('faq')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16), nullable=False),
    sa.Column('keywords', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('question', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=False),
    sa.Column('answer', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_faq_category'), 'faq', ['category'], unique=False)
    op.create_table('tickets',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False),
    sa.Column('ticket_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16), nullable=False),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('contact', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16), nullable=False),
    sa.Column('priority', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=4), nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('building', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=True),
    sa.Column('location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True),
    sa.Column('dept', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=True),
    sa.Column('repairman_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=True),
    sa.Column('escalation_count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('escalated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('closed_at', mysql.DATETIME(), nullable=True),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('review_comment', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('reviewed_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['repairman_id'], ['repairmen.id'], name=op.f('fk_tickets_repairman_id_repairmen')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tickets_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_tickets_user_id'), 'tickets', ['user_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_table('announcements',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_announcements_region'), 'announcements', ['region'], unique=False)
    op.create_table('accounts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_no', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16), nullable=False),
    sa.Column('note', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_accounts_student_no'), 'accounts', ['student_no'], unique=True)
    op.create_table('ticket_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('from_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('to_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('actor', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('note', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_logs_ticket_id_tickets')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_ticket_logs_ticket_id'), 'ticket_logs', ['ticket_id'], unique=False)
    op.create_table('dorms',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('building', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False),
    sa.Column('room_range', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=True),
    sa.Column('manager', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True),
    sa.Column('note', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_dorms_building'), 'dorms', ['building'], unique=True)
    op.create_table('repairmen',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('dept', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False),
    sa.Column('trade', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False),
    sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('on_duty', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_repairmen_trade'), 'repairmen', ['trade'], unique=False)
    op.create_index(op.f('ix_repairmen_dept'), 'repairmen', ['dept'], unique=False)
    op.drop_index(op.f('ix_knowledge_entries_domain'), table_name='knowledge_entries')
    op.drop_table('knowledge_entries')
    op.drop_index(op.f('ix_bad_cases_user_id'), table_name='bad_cases')
    op.drop_index(op.f('ix_bad_cases_status'), table_name='bad_cases')
    op.drop_table('bad_cases')
    # ### end Alembic commands ###
