"""m4: user_profiles + ticket review fields

Revision ID: c62b33f98479
Revises: a724a4e6d581
Create Date: 2026-08-05 13:35:42.553306

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c62b33f98479"
down_revision: str | Sequence[str] | None = "a724a4e6d581"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("building", sa.String(length=32), nullable=True),
        sa.Column("frequent_categories", sa.String(length=128), nullable=False),
        sa.Column("last_ticket_summary", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_profiles_user_id_users")
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_profiles")),
    )
    op.add_column("tickets", sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("tickets", sa.Column("rating", sa.Integer(), nullable=True))
    op.add_column("tickets", sa.Column("review_comment", sa.Text(), nullable=True))
    op.add_column("tickets", sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickets", "reviewed_at")
    op.drop_column("tickets", "review_comment")
    op.drop_column("tickets", "rating")
    op.drop_column("tickets", "closed_at")
    op.drop_table("user_profiles")
    # ### end Alembic commands ###
